import networkx as nx
import random

def homophilic_stochastic_block_graph_assym(N, minority_fraction, h_ina, h_inb, h_out, seed=None):
    """Return homophilic random graph using a 2-block stochastic block model.

    A graph of N nodes is generated by assigning each node to either a minority
    (a) or majority (b) group, then placing edges between pairs of nodes with
    probabilities that depend on whether they share the same group or not.

    Parameters
    ----------
    N : int
        Number of nodes.
    minority_fraction : float
        Fraction of nodes belonging to the minority group.
    h_ina : float
        Within-group edge probability for minority (a–a), in [0, 1].
    h_inb : float
        Within-group edge probability for majority (b–b), in [0, 1].
    h_out : float
        Between-group edge probability for a–b and b–a, in [0, 1].
    seed : int, optional
        Seed for random number generator (default=None).

    Returns
    -------
    G : Graph
        An undirected stochastic block graph with homophilic structure.
    minority_nodes : list
        List of node indices belonging to the minority group.
    """

    if seed is not None:
        random.seed(seed)

    # Create empty graph with N nodes
    G = nx.Graph()
    minority_count = int(round(minority_fraction * N))

    # Randomly assign minority nodes
    minority_nodes = set(random.sample(range(N), minority_count))
    node_attribute = {}

    for n in range(N):
        if n in minority_nodes:
            G.add_node(n, color='#f2d138')  # same colors as BA generator
            node_attribute[n] = 'minority'
        else:
            G.add_node(n, color='#19bdff')
            node_attribute[n] = 'majority'

    # Stochastic block edge generation
    for i in range(N):
        attr_i = node_attribute[i]
        for j in range(i + 1, N):
            attr_j = node_attribute[j]

            # Determine edge probability based on block pair
            if attr_i == 'minority' and attr_j == 'minority':
                p = h_ina
            elif attr_i == 'majority' and attr_j == 'majority':
                p = h_inb
            else:
                p = h_out

            # Add edge with probability p
            if random.random() < p:
                G.add_edge(i, j)

    return G, list(minority_nodes)


if __name__ == '__main__':
    G_sbm, minority_nodes = homophilic_stochastic_block_graph_assym(
        N=100,
        minority_fraction=0.1,
        h_ina=0.3,
        h_inb=0.2,
        h_out=0.05,
        seed=42
    )
